# Generated by Django 4.2.3 on 2023-07-31 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_cartegory_id_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-id']},
        ),
    ]
